name: CI
on: [push, pull_request]
jobs:
  bats-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run makefile actions
        shell: 'script -q -e -c "bash {0}"' # work around tty issues
        env:
          TERM: linux # fix tput for tty issue work around
        run: make ci
